image: node:16-alpine

stages:
  - build
  - deploy

build-css:
    stage: build
    artifacts:
        untracked: false
        expire_in: 3 days
        name: "stylesheet-$CI_COMMIT_REF_NAME"
        paths:
            - themes/portfolio/assets/css/style.css
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - .yarn
            - node_modules/
    script:
        - cd themes/portfolio
        - yarn install --cache-folder .yarn
        - yarn build

build:
    stage: build
    needs: ["build-css"]
    image: klakegg/hugo:0.93.3-alpine-ci
    artifacts:
        untracked: false
        expire_in: 7 days
        name: "website-$CI_COMMIT_REF_NAME"
        paths:
            - public/
    script:
        - hugo

prepare:
    stage: deploy
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules/
            - .yarn
    script:
        - yarn install --cache-folder .yarn
    rules:
        - if: $CI_COMMIT_BRANCH == "preview"
        - if: $CI_COMMIT_BRANCH  =~ /v([0-9]+(\.[0-9]+)+)/

preview:
    stage: deploy
    needs: ["build", "prepare"]
    script:
        - npx netlify deploy --dir public/
    rules:
        - if: $CI_COMMIT_BRANCH == "preview"

deploy:
    stage: deploy
    needs: ["build", "prepare"]
    script:
        - npx netlify deploy --prod --dir public/
    rules:
        - if: $CI_COMMIT_BRANCH  =~ /v([0-9]+(\.[0-9]+)+)/