image: node:18-alpine

stages:
  - build
  - deploy

build:
    stage: build
    cache:
        key: 
            files:
                - package-lock.json
        paths:
          - node_modules/ 
    artifacts:
        untracked: false
        expire_in: 7 days
        name: "website-$CI_COMMIT_REF_NAME"
        paths:
            - dist/
    script:
        - npm install
        - npm run build
        - echo '/* /.netlify/functions/entry 404' > dist/_redirects

check:
    stage: build
    cache:
        key: 
            files:
                - package-lock.json
        paths:
          - node_modules/ 
    script:
        - npm install
        - npx eslint .
        - npx prettier . -c

deploy:
    stage: deploy
    needs: ["build", "check"]
    cache:
        key: 
            files:
                - package-lock.json
        paths:
          - node_modules/ 
    script:
        - npm install
        - npx netlify deploy --prod --dir dist/
    rules:
        - if: $CI_COMMIT_BRANCH  =~ /v([0-9]+(\.[0-9]+)+)/