baseURL = 'https://lorenzocapalbo.com/'
title = 'Lorenzo Capalbo'
languageCode = 'en-us'
defaultContentLanguage = 'en'
theme = 'portfolio'

enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '#'
    weight = 1
    [menu.main.params]
      icon = 'home'
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = 'projects'
    weight = 2
    [menu.main.params]
      icon = 'briefcase'
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = 'tags'
    weight = 3
    [menu.main.params]
      icon = 'tag'
  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '#contact'
    weight = 4
    [menu.main.params]
      icon = 'send'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.it]
    languageName = 'Italiano'
    weight = 2
  [[languages.it.menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '#'
    weight = 1
    [languages.it.menu.main.params]
      icon = 'home'
  [[languages.it.menu.main]]
    identifier = 'projects'
    name = 'Progetti'
    url = 'projects'
    weight = 2
    [languages.it.menu.main.params]
      icon = 'briefcase'
  [[languages.it.menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = 'tags'
    weight = 3
    [languages.it.menu.main.params]
      icon = 'tag'
  [[languages.it.menu.main]]
    identifier = 'contact'
    name = 'Contatta'
    url = '#contact'
    weight = 4
    [languages.it.menu.main.params]
      icon = 'send'
[params]
  author = 'Lorenzo Capalbo'
  description = "I design and build software products"
  og_image = 'img/og.png'
  twitter_image = 'img/twitter.png'
  mail = 'capalbo.lorenzo@tutanota.com'
  githubUser = 'KL-B0'
  gitlabUser = 'KLB0'
  linkedinUser = 'lorenzo-capalbo-0424b3229'
  
  analytics = 'G-3BG24WNV4C'
